#!/usr/bin/env bash
set -e

XSOCK=/tmp/.X11-unix
XAUTH=/tmp/.docker.xauth

case "$1" in
    build-docker)
        docker build -t robotics_intro -f docker/Dockerfile .
        ;;
    run)
        docker run -it --rm \
            --name robotics_intro \
            --gpus all \
            --device /dev/dri:/dev/dri \
            --env="QT_X11_NO_MITSHM=1" \
            --env="DISPLAY" \
            -v "$XSOCK:$XSOCK:rw" \
            -v "$XAUTH:$XAUTH:rw" \
            -v "/tmp/.X11-unix:/tmp/.X11-unix:rw" \
            -v "$(pwd)":/opt/ws/src/code \
            --env="XAUTHORITY=$XAUTH" \
            robotics_intro
        ;;
    bash)
        docker exec -it robotics_intro bash
        ;;
    build-workspace)
        docker exec -it robotics_intro bash -c "cd /opt/ws && colcon build"
        ;;
    *)
        echo "Usage: $0 {build-docker|run|bash|build-workspace}"
        exit 1
        ;;
esac
